apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crd
  namespace: linkerd      
spec:
  project: default
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.8.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true